name: Update responses folder

on:
  workflow_dispatch:

jobs:
  bruteforce:
    strategy:
      fail-fast: false
      matrix:
        client: [27,56]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Update responses folder
        run: python innerbrute.py ${{ matrix.client }}
      - uses: EndBug/add-and-commit@v9
        id: commit
        continue-on-error: true
        with:
          message: 'Add clients for ${{ matrix.client }}'
          pull: '--rebase --autostash'
      - name: re-commit
        id: commit2
        if: steps.commit.outcome == 'failure'
        continue-on-error: true
        run: (git pull --rebase&&git push)||(git pull --rebase&&git push)
      - name: re-commit
        id: commit3
        if: steps.commit2.outcome == 'failure'
        continue-on-error: true
        run: (git pull --rebase&&git push)||(git pull --rebase&&git push)
      - name: re-commit
        id: commit4
        if: steps.commit3.outcome == 'failure'
        continue-on-error: true
        run: (git pull --rebase&&git push)||(git pull --rebase&&git push)
      - name: re-commit
        if: steps.commit4.outcome == 'failure'
        run: (git pull --rebase&&git push)||(git pull --rebase&&git push)
