name: Update responses folder

on:
  workflow_dispatch:

jobs:
  bruteforce:
    strategy:
      fail-fast: false
      matrix:
        client: [1,2,3,5,7,14,15,18,19,21,23,26,27,28,29,33,39,41,43,55,56,57,59,62,63,64,65,67,74,75,76,85,88,93,98]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update responses folder
        run: python innerbrute.py ${{ matrix.client }}
