name: Update responses folder

on:
  workflow_dispatch:

jobs:
  bruteforce:
    strategy:
      fail-fast: false
      matrix:
        client: [3,10,14,18,21,23,28,29,30,38,55,63,74]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Update responses folder
        run: python innerbrute.py ${{ matrix.client }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Add clients for ${{ matrix.client }}'
          pull: '--rebase --autostash'
