name: Update responses folder

on:
  workflow_dispatch:

jobs:
  bruteforce:
    strategy:
      fail-fast: false
      matrix:
        client: [1,2,3,5,7,8,10,13,14,15,16,18,19,21,23,26,27,28,29,30,31,33,38,39,41,42,43,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,74,75,76,77,80,84,85,87,88,89,90,92,93,94,95,98,99,100,101]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update responses folder
        run: python innerbrute.py ${{ matrix.client }}
