name: Update responses folder

on:
  workflow_dispatch:

jobs:
  bruteforce:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update responses folder
        run: python innerbrute.py 
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update responses folder'
